name: SonarQube Scan

on:
  workflow_call:

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.GLOBAL_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.GLOBAL_SONAR_HOST_URL }}
